language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/registration_app_database

node_js:  
  - "8.9.4"

before_script:
  - psql -c 'create database  registration_app_database;' -U postgres
  - psql -U postgres -d registration_app_database -a -f public/sqlFile(s)/sqlTemplate.sql
  - psql -U postgres -d registration_app_database -a -f public/sqlFile(s)/insertTowns.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2